name: Build
on: [push, pull_request]

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                python-version: [3.6, 3.7, 3.8]
                os: [ubuntu-18.04]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - run: |
                pip3 install poetry
                poetry install
                source $(poetry env info --path)/bin/activate
                poetry build
